// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeMode } from "./ThemeMode";
import type { TimeDisplayConfig } from "./TimeDisplayConfig";

export type AppearanceConfig = {
  theme: ThemeMode;
  language: string;
  timeDisplay: TimeDisplayConfig;
  /**
   * Derive each game's chart color from its cover image. When off, the
   * statistics page falls back to a deterministic golden-angle palette.
   */
  extractCoverColor: boolean;
};
